name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          npm install
          npm run build

      - name: Archive distribution bundle
        uses: actions/upload-artifact@v4
        with:
          path: dist/config-template-card.js
          name: config-template-card-latest-build.js
          overwrite: true
