name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cd /home/runner/work/config-template-card/config-template-card
          yarn install
          npm run build

      - name: Upload as release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/config-template-card/config-template-card/dist/config-template-card.js
          asset_name: config-template-card.js
          tag: ${{ github.ref }}
          overwrite: true
