name: Test Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_build:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          npm install
          npm run build
